#166240784 Enables users  to create new article
andela/savage_rangers-ah-frontend pull request #15
Opened 2019-08-16 06:28 UTC by truestbyheart

#### What does this PR do?
* It enables the user to create new articles

#### Description of Task to be completed?
 * Create a UI page for creating article
#### How should this be manually tested?
* Clone the repo to the local machine.
* Run ``npm install``   to install the dependencies.
* Set up the   ``.env`` as instructed by the   ``.env-example``
* Run  ``npm start``.
* Send a GET request to ``/new``.
#### What are the relevant pivotal tracker stories?
#[166240784](https://www.pivotaltracker.com/story/show/166240784)

2019-08-21 11:51 UTC, bdushimi requested changes

2019-08-21 11:51 UTC, bdushimi commented on src/Redux/Actions/articles.js
> +};
@truestbyheart, The thunk name is not specific enough to reflect what it does actually! The thunk says changeState but the dispatched action is to update article state. Additionally, I think there's no need to add _STATE suffix, at the end of the day a dispatched action will always update the state.

2019-08-21 11:51 UTC, bdushimi commented on src/Redux/Reducers/createArticle.js
> +    case PUBLISH_ARTICLE:
@truestbyheart wouldn't be better to export one variable and have 1 switch statement block instead of two?

2019-08-21 20:49 UTC, MCFrank16 commented on src/App/_tests_/createArticle.test.js
> +        article: { body: 'Can i get an Amen' }
boy you need the holy spirit for sure!!!

2019-08-22 19:00 UTC, nkpremices approved these changes
Good job man

2019-08-22 19:00 UTC, nkpremices commented on src/App/Components/CreateArticle/CreateArticle.js
> +            .then(() => {
I like this idea @truestbyheart

2019-08-26 17:53 UTC, alainburindi approved these changes

2019-08-26 17:53 UTC, alainburindi commented on src/App/_tests_/setup/setupEnzyme.js
> +import Enzyme from 'enzyme';
we don't need this file

2019-08-26 17:53 UTC, alainburindi commented on public/index.html
> +</html>
new line

2019-08-26 17:56 UTC, Ramadhan0 approved these changes

2019-08-26 19:44 UTC, merged