#168049548  Fetch all authors
andela/savage_rangers-ah-frontend pull request #23
Opened 2019-09-01 15:37 UTC by murediane

#### What does this PR do?
Fetch all authors
#### Description of Task to be completed?
get all authors  profile details
#### How should this be manually tested?
open the browser and go to this URL https://authors-haven-staging.herokuapp.com/authors
#### Any background context you want to provide?
 Follow and unfollow ,Search is designed but the functionalities are not implemented
#### What are the relevant pivotal tracker stories?
[168049548](https://www.pivotaltracker.com/story/show/168049548)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-09-01 at 17 36 05" src="https://user-images.githubusercontent.com/26599052/64078761-04b11c00-ccdf-11e9-85f0-cc582ab95e6b.png">

2019-09-10 18:22 UTC, Ramadhan0 approved these changes

2019-09-10 18:22 UTC, Ramadhan0 commented on src/Style/Sass/layout/_authors.scss
> +// }
@murediane why do you have this commented code???

2019-09-10 18:22 UTC, Ramadhan0 commented on src/Style/Sass/layout/_editor.scss
> +// .DraftEditor {
@murediane if you are using this file please remove it

2019-09-10 18:22 UTC, Ramadhan0 commented on src/configs/axios.js
> +// const baseURL = 'http://localhost:3001/';
same here @murediane why do you have this in your code???

2019-09-11 08:13 UTC, alainburindi requested changes

2019-09-11 08:13 UTC, alainburindi commented on src/App/Components/authors/authorcomponent/index.js
> +        </div>
new line

2019-09-11 08:13 UTC, alainburindi commented on src/App/_tests_/Redux/Reducers/authors.test.js
> +        authors: [
can you reduce this array's length?

2019-09-11 08:13 UTC, alainburindi commented on src/App/_tests_/Redux/Reducers/authors.test.js
> +        {
What do you think if you put this array in a constant then you expect that constant? to avoid duplication

2019-09-11 08:13 UTC, alainburindi commented on src/Style/Sass/layout/_editor.scss
> +// .DraftEditor {
why did you comment this file?

2019-09-11 08:13 UTC, alainburindi commented on src/Style/Sass/pages/_ArticleNotFound.scss
> +  }
I think @MCFrank16 has removed this file

2019-09-11 11:10 UTC, alainburindi approved these changes

2019-09-11 11:27 UTC, nkpremices commented
@murediane please rebase

2019-09-11 12:50 UTC, MemunaHaruna commented on src/App/Components/authors/authorcomponent/index.js
> +        </div>
@murediane

2019-09-11 12:51 UTC, MemunaHaruna commented on src/App/_tests_/authors.test.js
> +  beforeEach(() => {
@murediane are you clearing these after the test?

2019-09-11 13:00 UTC, MemunaHaruna approved these changes

2019-09-11 13:07 UTC, merged